package:
  name: pnumpy
  version: "1.3.0"

source:
  fn: pnumpy-1.3.0.tar.gz
  url: https://pypi.python.org/packages/2e/9e/f1d67aa623b249ade447e917b618f4638648ec44d1fe164ae058526088e3/pnumpy-1.3.0.tar.gz
  md5: a848e7ce3137b742595856c6f3ffb0b2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pnumpy = pnumpy:main
    #
    # Would create an entry point called pnumpy that calls pnumpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - mpi4py >=2.0.0

  run:
    - python
    - numpy >=1.10
    - mpi4py >=2.0.0

test:
  # Python imports
  imports:
    - pnumpy

about:
  home: https://github.com/pletzer/pnumpy.git
  license: MIT
  summary: 'A very lightweight implementation of distributed arrays'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
