package:
  name: pnumpy
  version: "1.3.1"

source:
  fn: pnumpy-1.3.1.tar.gz
  url: https://pypi.python.org/packages/bf/1d/6901aa3bc538923e3f398226e9aa470e231e3c589cf3303c10cc04de6a8f/pnumpy-1.3.1.tar.gz
  md5: e283aaf85d86372a9cfdf88e948f3dfe
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pnumpy = pnumpy:main
    #
    # Would create an entry point called pnumpy that calls pnumpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - mpi4py >=2.0.0

  run:
    - python
    - numpy >=1.10
    - mpi4py >=2.0.0

test:
  # Python imports
  imports:
    - pnumpy

about:
  home: https://github.com/pletzer/pnumpy.git
  license: MIT
  summary: 'A very lightweight implementation of distributed arrays'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
