package:
  name: pnumpy
  version: "1.3.3"

source:
  fn: pnumpy-1.3.3.tar.gz
  url: https://pypi.python.org/packages/13/a6/dc35440cddd4642264b2584f2c32f81c296bb821ee6532fab3184392baa8/pnumpy-1.3.3.tar.gz
  md5: af477b66f74aa8282e48631ca3771bf4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pnumpy = pnumpy:main
    #
    # Would create an entry point called pnumpy that calls pnumpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - mpi4py >=2.0.0

  run:
    - python
    - numpy >=1.10
    - mpi4py >=2.0.0

test:
  # Python imports
  imports:
    - pnumpy

about:
  home: https://github.com/pletzer/pnumpy.git
  license: MIT
  summary: 'A very lightweight implementation of distributed arrays'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
