package:
  name: mpinum
  version: "1.3.4"

source:
  fn: mpinum-1.3.4.tar.gz
  url: https://pypi.python.org/packages/21/2b/ab5ece8ba23289bd00dd880e22fa545b1322f8f486d668f8c0e55d8c8f5a/mpinum-1.3.4.tar.gz
  md5: b8225fbe9c08647a974c059c0eb6ad53
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mpinum = mpinum:main
    #
    # Would create an entry point called mpinum that calls mpinum.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - mpi4py >=2.0.0

  run:
    - python
    - numpy >=1.10
    - mpi4py >=2.0.0

test:
  # Python imports
  imports:
    - mpinum

about:
  home: https://github.com/pletzer/mpinum.git
  license: MIT
  summary: 'A very lightweight implementation of distributed arrays'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
